repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: "main.*"
  - repo: https://github.com/lovesegfault/beautysh
    rev: "v6.2.1"
    hooks:
      - id: beautysh
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.30.0"
    hooks:
      - id: yamllint
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=140]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.4.4"
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
